'use strict'

exports.layerKey = {
  map_collar: 'Map_Collar',
  map_collar_elements: 'Map_Collar.Map_Elements',
  map_frame: 'Map_Frame',
  projection_and_grid: 'Map_Frame.Projection_and_Grids',
  geographic_names: 'Map_Frame.Geographic_Names',
  structures: 'Map_Frame.Structures',
  transportation: 'Map_Frame.Transportation',
  road_names: 'Map_Frame.Transportation.Road_Names_and_Shields',
  road_features: 'Map_Frame.Transportation.Road_Features',
  trails: 'Map_Frame.Transportation.Trails',
  railroads:'Map_Frame.Transportation.Railroads',
  airports:'Map_Frame.Transportation.Airports',
  plss: 'Map_Frame.PLSS',
  hydrography: 'Map_Frame.Hydrography',
  terrain: 'Map_Frame.Terrain',
  contours: 'Map_Frame.Terrain.Contours',
  shaded_relief: 'Map_Frame.Terrain.Shaded_Relief',
  woodland: 'Map_Frame.Woodland',
  boundaries: 'Map_Frame.Boundaries',
  jurisdictional_boundaries: 'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  international_boundaries: 'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  state_boundaries: 'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  county_boundaries: 'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  federal_lands: 'Map_Frame.Boundaries.Federal_Administered_Lands',
  national_park_lands: 'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  department_of_defense_lands: 'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  forest_service_lands: 'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  images: 'Images',
  ortho_imagery: 'Images.Orthoimage',
  barcode: 'Barcode'
};

exports.clipping = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Barcode'
];

exports.all = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Map_Frame.Geographic_Names',
  'Map_Frame.Structures',
  'Map_Frame.Transportation',
  'Map_Frame.Transportation.Road_Names_and_Shields',
  'Map_Frame.Transportation.Road_Features',
  'Map_Frame.Transportation.Trails',
  'Map_Frame.Transportation.Railroads',
  'Map_Frame.Transportation.Airports',
  'Map_Frame.PLSS',
  'Map_Frame.Hydrography',
  'Map_Frame.Terrain',
  'Map_Frame.Terrain.Contours',
  'Map_Frame.Terrain.Shaded_Relief',
  'Map_Frame.Woodland',
  'Map_Frame.Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  'Map_Frame.Boundaries.Federal_Administered_Lands',
  'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  'Images',
  'Images.Orthoimage',
  'Barcode'
];

exports.imagery = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Map_Frame.Geographic_Names',
  'Map_Frame.Structures',
  'Map_Frame.Transportation',
  'Map_Frame.Transportation.Road_Names_and_Shields',
  'Map_Frame.Transportation.Road_Features',
  'Map_Frame.Transportation.Trails',
  'Map_Frame.Transportation.Railroads',
  'Map_Frame.Transportation.Airports',
  'Map_Frame.Hydrography',
  'Map_Frame.Woodland',
  'Map_Frame.Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  'Map_Frame.Boundaries.Federal_Administered_Lands',
  'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  'Images',
  'Images.Orthoimage',
  'Barcode'
];

exports.terrain = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Map_Frame.Geographic_Names',
  'Map_Frame.Structures',
  'Map_Frame.Transportation',
  'Map_Frame.Transportation.Road_Names_and_Shields',
  'Map_Frame.Transportation.Road_Features',
  'Map_Frame.Transportation.Trails',
  'Map_Frame.Transportation.Railroads',
  'Map_Frame.Transportation.Airports',
  'Map_Frame.Hydrography',
  'Map_Frame.Terrain',
  'Map_Frame.Terrain.Contours',
  'Map_Frame.Terrain.Shaded_Relief',
  'Map_Frame.Woodland',
  'Map_Frame.Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  'Map_Frame.Boundaries.Federal_Administered_Lands',
  'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  'Barcode'
];


exports.carto = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Map_Frame.Geographic_Names',
  'Map_Frame.Structures',
  'Map_Frame.Transportation',
  'Map_Frame.Transportation.Road_Names_and_Shields',
  'Map_Frame.Transportation.Road_Features',
  'Map_Frame.Transportation.Trails',
  'Map_Frame.Transportation.Railroads',
  'Map_Frame.Transportation.Airports',
  'Map_Frame.PLSS',
  'Map_Frame.Hydrography',
  'Map_Frame.Terrain',
  'Map_Frame.Terrain.Contours',
  'Map_Frame.Woodland',
  'Map_Frame.Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  'Map_Frame.Boundaries.Federal_Administered_Lands',
  'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  'Barcode'
];


exports.cartoNoLabels = [
  'Map_Collar',
  'Map_Collar.Map_Elements',
  'Map_Frame',
  'Map_Frame.Projection_and_Grids',
  'Map_Frame.Structures',
  'Map_Frame.Transportation',
  'Map_Frame.Transportation.Road_Features',
  'Map_Frame.Transportation.Trails',
  'Map_Frame.Transportation.Railroads',
  'Map_Frame.Transportation.Airports',
  'Map_Frame.PLSS',
  'Map_Frame.Hydrography',
  'Map_Frame.Terrain',
  'Map_Frame.Terrain.Contours',
  'Map_Frame.Woodland',
  'Map_Frame.Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.International',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.State_or_Territory',
  'Map_Frame.Boundaries.Jurisdictional_Boundaries.County_or_Equivalent',
  'Map_Frame.Boundaries.Federal_Administered_Lands',
  'Map_Frame.Boundaries.Federal_Administered_Lands.National_Park_Service',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Department_of_Defense',
  'Map_Frame.Boundaries.Federal_Administered_Lands.Forest_Service',
  'Barcode'
];
